apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment  # Changed the name to reflect Tomcat deployment
  labels:
    app: tomcat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
      - name: tomcat-container  # Changed container name to reflect Tomcat
        image: rohitp779/trainproject  # Using the Tomcat image
        ports:
        - containerPort: 8080  # Assuming Tomcat runs on port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service  # Changed the service name to reflect Tomcat service
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - port: 80
      targetPort: 8080  # Match with the container port for Tomcat
      nodePort: 30007  # NodePort for accessing Tomcat externally
